CREATE DATABASE IF NOT EXISTS sistema_usuarios CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sistema_usuarios;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);
